#!/usr/bin/env python3
"""
Codegen for the P3 metagame content:
  fusions.authored.json   -> game/engine/content/fusions.generated.ts   (FusionForm[])
  augments.authored.json  -> game/engine/content/augments.generated.ts  (Augment[])

Emitting typed TS literals means `tsc` fully checks every fusion skill / augment patch (a bad
op/shape is a compile error) — the strong half of the "compilation is the oracle" pipeline.
Reuses the roster codegen's skill/trigger normalisers (strip authoring-only keys, add currentCd,
default trigger source/effect).

Usage: python game/tools/build_p3.py
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_roster as br  # reuse strip_notes / clean_skill / norm_triggers

CONTENT = os.path.join(HERE, "..", "content")
ENGINE = os.path.join(HERE, "..", "engine", "content")


def norm_one_trigger(t, default_source):
    return br.norm_triggers([t], default_source)[0]


# Valid keys per patch op — anything else an agent added (e.g. a stray top-level "source" on
# addTrigger, or "note") is dropped so the emitted literal matches the Patch union exactly.
PATCH_KEYS = {
    "addTrigger": {"op", "trigger"},
    "removeTrigger": {"op", "source"},
    "addSkill": {"op", "skill", "slot"},
    "replaceSkill": {"op", "skillId", "skill"},
    "setSkillMeta": {"op", "skillId", "meta"},
    "appendEffect": {"op", "skillId", "effect"},
    "patchNode": {"op", "skillId", "nodeId", "replace"},
    "custom": {"op", "fn", "args"},
}


def clean_patch(p):
    op = p.get("op")
    default_source = p.get("source") or "augment"  # a stray top-level source becomes the trigger's
    p = br.strip_notes(p)
    if op == "addTrigger" and isinstance(p.get("trigger"), dict):
        p["trigger"] = norm_one_trigger(p["trigger"], default_source)
    elif op in ("addSkill", "replaceSkill") and isinstance(p.get("skill"), dict):
        p["skill"] = br.clean_skill(p["skill"])
    allowed = PATCH_KEYS.get(op, {"op"})
    return {k: v for k, v in p.items() if k in allowed}


def clean_augment(a):
    out = {"id": a["id"], "name": a.get("name", a["id"]), "description": a.get("description", "")}
    if a.get("owner"):
        out["owner"] = a["owner"]
    out["patches"] = [clean_patch(p) for p in (a.get("patches") or [])]
    return out


def clean_form(f):
    passive = f.get("passive") or {}
    out = {
        "key": f["key"], "hero": f["hero"], "element": f["element"],
        "passive": {"name": passive.get("name", "Fusion"), "description": passive.get("description", "")},
        "passiveTriggers": br.norm_triggers(f.get("passiveTriggers"), passive.get("name") or "fusion"),
        "skill": br.clean_skill(f["skill"]),
    }
    if f.get("passiveMode"):
        out["passiveMode"] = f["passiveMode"]
    if f.get("slot") is not None:
        out["slot"] = f["slot"]
    return out


def emit_fusions(forms):
    cleaned = [clean_form(f) for f in forms]
    parts = [
        "// AUTO-GENERATED by game/tools/build_p3.py from fusions.authored.json — do not edit by hand.",
        'import type { FusionForm } from "./fusion.ts";',
        "",
        "export const FUSIONS: FusionForm[] = " + json.dumps(cleaned, indent=1, ensure_ascii=False) + ";",
        "",
        "const BY_KEY = new Map<string, FusionForm>(FUSIONS.map((f) => [`${f.hero}:${f.key}`, f]));",
        "export function fusionForm(hero: string, key: string): FusionForm | undefined { return BY_KEY.get(`${hero}:${key}`); }",
        "export function fusionsFor(hero: string): FusionForm[] { return FUSIONS.filter((f) => f.hero === hero); }",
        "",
    ]
    out = os.path.join(ENGINE, "fusions.generated.ts")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))
    return out, len(cleaned)


def emit_augments(augs):
    cleaned = [clean_augment(a) for a in augs]
    parts = [
        "// AUTO-GENERATED by game/tools/build_p3.py from augments.authored.json — do not edit by hand.",
        'import type { Augment } from "./augment.ts";',
        "",
        "export const AUGMENTS: Augment[] = " + json.dumps(cleaned, indent=1, ensure_ascii=False) + ";",
        "",
        "const BY_ID = new Map<string, Augment>(AUGMENTS.map((a) => [a.id, a]));",
        "export function augmentById(id: string): Augment | undefined { return BY_ID.get(id); }",
        "export function augmentsFor(hero: string): Augment[] { return AUGMENTS.filter((a) => a.owner === hero); }",
        "",
    ]
    out = os.path.join(ENGINE, "augments.generated.ts")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(parts))
    return out, len(cleaned)


def load(name):
    p = os.path.join(CONTENT, name)
    if not os.path.exists(p):
        return None
    return json.load(open(p, encoding="utf-8"))


def main():
    fd = load("fusions.authored.json")
    ad = load("augments.authored.json")
    if fd is not None:
        forms = fd.get("forms", fd) if isinstance(fd, dict) else fd
        out, n = emit_fusions(forms)
        print(f"wrote {out}: {n} fusion forms")
    if ad is not None:
        augs = ad.get("augments", ad) if isinstance(ad, dict) else ad
        out, n = emit_augments(augs)
        print(f"wrote {out}: {n} augments")


if __name__ == "__main__":
    main()
