#!/usr/bin/env python3
"""
Codegen: roster.authored.json -> game/content/roster.generated.ts (typed HeroDef[]).

Emitting the authored content as TypeScript LITERALS typed `HeroDef[]` / `MinionTemplate[]`
means `tsc` fully checks every discriminated-union node (a bad op/kind/shape is a compile
error) — the second, strongest half of the "compilation is the oracle" pipeline. json.dumps
output is valid TS object-literal syntax, and a literal assigned to a typed target narrows
correctly, so the check is real.

Transforms applied: add currentCd:0 to every SkillInstance; merge the passive's trigger into
the hero's triggers; default a missing trigger `source`; collect + de-dupe minion templates.

Usage: python game/tools/build_roster.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "content", "roster.authored.json")
# The engine consumes content from game/engine/content/ (next to hero.ts).
OUT = os.path.join(HERE, "..", "engine", "content", "roster.generated.ts")


# Authoring-only / deferred-cosmetic keys that are not valid engine fields.
COSMETIC_KEYS = {"note", "invisible", "hidden", "hidden_targets"}  # isHidden is now a real per-skill flag (kept)


def strip_notes(obj):
    """Recursively drop authoring-only / cosmetic keys (documentation notes, status-level `invisible`
    redaction flags, frozen `hidden`/`hidden_targets` leakage). The per-skill `isHidden` flag is REAL and kept."""
    if isinstance(obj, dict):
        return {k: strip_notes(v) for k, v in obj.items() if k not in COSMETIC_KEYS}
    if isinstance(obj, list):
        return [strip_notes(x) for x in obj]
    return obj


SKILL_FIELDS = {"id", "name", "element", "targeting", "targetKind", "effects", "cost", "cooldown",
                "klass", "tags", "channelTurns", "doesNotInterrupt", "requires", "uncounterableIf", "costMods", "isHidden",
                "doesNotBreakVeil"}


def clean_skill(s):
    """Keep only valid SkillInstance fields (drops frozen-data leakage like hidden_targets)."""
    s = strip_notes(s)
    out = {k: v for k, v in s.items() if k in SKILL_FIELDS}
    out["currentCd"] = 0
    return out


def with_cd(skills):
    return [clean_skill(s) for s in (skills or [])]


def norm_triggers(triggers, default_source):
    out = []
    for t in triggers or []:
        t = strip_notes(t)
        t.setdefault("source", default_source)
        t.setdefault("effect", [])  # a redirect-only reflect still needs an (empty) effect list
        out.append(t)
    return out


def main():
    data = json.load(open(SRC, encoding="utf-8"))
    heroes = data.get("heroes", data)

    minions = {}
    hero_defs = []
    for h in heroes:
        passive = h.get("passive") or {}
        triggers = norm_triggers(h.get("triggers"), passive.get("name") or "passive")
        if isinstance(passive.get("trigger"), dict):
            triggers.extend(norm_triggers([passive["trigger"]], passive.get("name") or "passive"))
        passive_def = {"name": passive.get("name", "Passive"), "description": passive.get("description", "")}
        if passive.get("note"):
            passive_def["pending"] = passive["note"]
        hero_defs.append({
            "id": h["id"], "name": h["name"], "element": h["element"], "maxHp": h["maxHp"],
            "passive": passive_def, "skills": with_cd(h.get("skills")), "triggers": triggers,
        })
        for m in h.get("minions") or []:
            if m["name"] in minions:
                continue
            entry = {"name": m["name"], "maxHp": m["maxHp"]}
            if m.get("element"):
                entry["element"] = m["element"]
            entry["skills"] = with_cd(m.get("skills"))
            entry["triggers"] = norm_triggers(m.get("triggers"), m["name"])
            minions[m["name"]] = entry

    parts = [
        "// AUTO-GENERATED by game/tools/build_roster.py from roster.authored.json — do not edit by hand.",
        'import type { HeroDef } from "./hero.ts";',
        'import type { MinionTemplate } from "../src/minions.ts";',
        'import { registerMinion } from "../src/minions.ts";',
        "",
        "export const MINIONS: MinionTemplate[] = " + json.dumps(list(minions.values()), indent=1, ensure_ascii=False) + ";",
        "for (const m of MINIONS) registerMinion(m);",
        "",
        "export const ROSTER: HeroDef[] = " + json.dumps(hero_defs, indent=1, ensure_ascii=False) + ";",
        "",
    ]
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(parts))
    print(f"wrote {OUT}: {len(hero_defs)} heroes, {len(minions)} minion templates")


if __name__ == "__main__":
    main()
