#!/usr/bin/env python3
"""Bundle the exported JSON database + an asset index into app/db.js.

The Element Arena Explorer is a static, dependency-free web app. To let it run
by simply double-clicking index.html (file:// blocks fetch() but not <img>),
we embed the whole database as a JS global. Re-run this after re-exporting:

    python build_data.py

It reads output/database.json and walks assets/ so the app knows which
portrait / fusion-form images actually exist on disk.
"""
import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.path.join(ROOT, "output", "database.json")
ASSETS_DIR = os.path.join(ROOT, "assets")
OUT_PATH = os.path.join(ROOT, "app", "db.js")


def load_db():
    with open(DB_PATH, encoding="utf-8") as f:
        return json.load(f)


def index_assets():
    """Every .png under assets/, as repo-relative forward-slash paths."""
    paths = []
    if not os.path.isdir(ASSETS_DIR):
        return paths
    for dirpath, _dirs, files in os.walk(ASSETS_DIR):
        for name in files:
            if name.lower().endswith(".png"):
                rel = os.path.relpath(os.path.join(dirpath, name), ROOT)
                paths.append(rel.replace(os.sep, "/"))
    paths.sort()
    return paths


def main():
    db = load_db()
    assets = index_assets()
    os.makedirs(os.path.dirname(OUT_PATH), exist_ok=True)
    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write("// AUTO-GENERATED by build_data.py — do not edit by hand.\n")
        f.write("// Re-run `python build_data.py` after re-exporting the database.\n")
        f.write("window.GAME_DB = ")
        json.dump(db, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
        f.write("window.ASSETS_INDEX = ")
        json.dump(assets, f, ensure_ascii=False, separators=(",", ":"))
        f.write(";\n")
    counts = db.get("_meta", {}).get("counts", {})
    size_kb = os.path.getsize(OUT_PATH) / 1024
    print(f"Wrote {OUT_PATH} ({size_kb:.0f} KB)")
    print(f"  characters={counts.get('characters')} skills={counts.get('skills')} "
          f"augments={counts.get('augments')} minions={counts.get('minions')} "
          f"elements={counts.get('elements')}")
    print(f"  asset index: {len(assets)} png files")


if __name__ == "__main__":
    main()
