"""Generate elementid.generated.ts: element id -> name, from frozen/elements.json.

Skill descriptions embed energy references as [<element id>] (e.g. [65] = generic); the client
turns each into the matching energy-tooltip icon. This map resolves the id -> element name.
Run from repo root: python game/web/tools/gen_elementid.py
"""
import json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
data = json.load(open(os.path.join(ROOT, "game/content/frozen/elements.json"), encoding="utf-8"))

pairs = {int(e["id"]): e["name"] for e in data["elements"]}

lines = [
    "/**",
    " * element id -> name, from frozen/elements.json.",
    " * Generated by game/web/tools/gen_elementid.py — do not edit by hand.",
    " * Resolves the [<id>] energy references in skill descriptions to energy-tooltip icons.",
    " */",
    "export const ELEMENT_BY_ID: Record<number, string> = {",
]
for k in sorted(pairs):
    lines.append(f'  {k}: {json.dumps(pairs[k])},')
lines.append("};")

out = os.path.join(ROOT, "game/web/src/elementid.generated.ts")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"wrote {out}: {len(pairs)} elements  (65 -> {pairs.get(65)})")
