"""Generate skillicon.generated.ts: skill id -> committed icon path (page-relative).

Reads frozen/skills.json's `image` field, which resolves BOTH hero and minion skill
icons (including the irregular minion asset filenames) in one map. The 8 image-less
skills (darkness*, one aurora minion) fall back to the hero-folder path in assets.ts.
Run from repo root: python game/web/tools/gen_skillicon.py
"""
import json, os, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
skills = json.load(open(os.path.join(ROOT, "game/content/frozen/skills.json"), encoding="utf-8"))

pairs = {}
missing = []
for s in skills:
    img = s.get("image")
    if not img:
        continue
    p = img.replace("\\", "/")
    pairs[s["id"]] = "../../" + p
    if not os.path.exists(os.path.join(ROOT, p)):
        missing.append((s["id"], p))

if missing:
    print(f"WARNING: {len(missing)} mapped icon files not found on disk:", file=sys.stderr)
    for i in missing[:20]:
        print("   ", i, file=sys.stderr)

lines = [
    "/**",
    " * skill id -> committed icon path (page-relative), from frozen/skills.json's `image` field.",
    " * Generated by game/web/tools/gen_skillicon.py — do not edit by hand.",
    " * Covers hero AND minion skills (the image field resolves the irregular minion filenames);",
    " * the few image-less skills fall back to the hero-folder path in assets.ts.",
    " */",
    "export const SKILL_ICON: Record<string, string> = {",
]
for k in sorted(pairs):
    lines.append(f'  {json.dumps(k)}: {json.dumps(pairs[k])},')
lines.append("};")

out = os.path.join(ROOT, "game/web/src/skillicon.generated.ts")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"wrote {out}: {len(pairs)} icons, {len(missing)} missing")
