"""Generate glossref.generated.ts: skill- and minion-NAME references for the in-match hover glossary.

Every skill/minion name that appears in hover text becomes a hover link that opens a small card (cost, CD,
element, HP, owner, description). Names are matched case-sensitively (unlike the case-insensitive mechanical
keywords). Reads output/glossary.json (the authoritative name -> id reference tables) and enriches each with
card details from output/database.json. Descriptions are reused from skilltext.generated.ts at runtime, so
they're NOT duplicated here. Run from repo root: python game/web/tools/gen_glossref.py
"""
import json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
gloss = json.load(open(os.path.join(ROOT, "output/glossary.json"), encoding="utf-8"))
db = json.load(open(os.path.join(ROOT, "output/database.json"), encoding="utf-8"))

chars = db.get("characters", [])
char_name = {c["id"]: (c.get("short_name") or c.get("character_name") or c["id"]) for c in chars}
skills_by_id = {s["id"]: s for s in db.get("skills", [])}
minions_by_id = {m["id"]: m for m in db.get("minions", [])}


def elem_name(obj):
    e = obj.get("element") if obj else None
    return (e or {}).get("name", "") if isinstance(e, dict) else ""


# 1. skill name -> id (first occurrence wins on a name collision), plus a card per referenced id.
skill_refs, skill_cards, seen_name = [], {}, set()
for r in gloss.get("skill_references", []):
    name, sid = r.get("name"), r.get("skill_id")
    if not name or not sid:
        continue
    s = skills_by_id.get(sid)
    if sid not in skill_cards:
        cost = (s or {}).get("cost", {}) or {}
        tt = (s or {}).get("targeting_type") or {}
        skill_cards[sid] = {
            "name": (s or {}).get("name", name),
            "gen": int(cost.get("generic", 0)),
            "spec": int(cost.get("specific", 0)),
            "elem": elem_name(s),
            "cd": int((s or {}).get("cooldown", 0)),
            "passive": bool((s or {}).get("is_passive", False)),
            "target": (tt.get("name") or "") if isinstance(tt, dict) else "",
            "owner": char_name.get((s or {}).get("owner", ""), ""),
        }
    if name in seen_name:
        continue
    seen_name.add(name)
    skill_refs.append({"name": name, "id": sid})

# 2. minion name -> card (first occurrence wins; a name already used by a skill is skipped, matching the codex).
minion_refs = []
for r in gloss.get("minion_references", []):
    name, mid = r.get("name"), r.get("minion_id")
    if not name or name in seen_name:
        continue
    seen_name.add(name)
    m = minions_by_id.get(mid)
    minion_refs.append({
        "name": name, "id": mid,
        "hp": (None if r.get("hp_dynamic") else r.get("hp")),
        "hpDynamic": bool(r.get("hp_dynamic")),
        "elem": elem_name(m),
        "owner": char_name.get((m or {}).get("owner", ""), ""),
    })

j = lambda v: json.dumps(v)
lines = [
    "/**",
    " * Skill- and minion-NAME references for the in-match hover glossary. Matched case-sensitively; a hover",
    " * opens a card (cost / cooldown / element / HP / owner + the skill's own description, reused from",
    " * SKILL_TEXT at runtime). Generated by game/web/tools/gen_glossref.py from output/glossary.json +",
    " * output/database.json — do not edit by hand.",
    " */",
    "export interface SkillRef { name: string; id: string; }",
    "export interface SkillCard { name: string; gen: number; spec: number; elem: string; cd: number; passive: boolean; target: string; owner: string; }",
    "export interface MinionRef { name: string; id: string; hp: number | null; hpDynamic: boolean; elem: string; owner: string; }",
    "export const SKILL_REFS: SkillRef[] = [",
]
for r in skill_refs:
    lines.append(f'  {{ name: {j(r["name"])}, id: {j(r["id"])} }},')
lines.append("];")
lines.append("export const SKILL_CARDS: Record<string, SkillCard> = {")
for sid, c in skill_cards.items():
    lines.append(
        f'  {j(sid)}: {{ name: {j(c["name"])}, gen: {c["gen"]}, spec: {c["spec"]}, elem: {j(c["elem"])}, '
        f'cd: {c["cd"]}, passive: {"true" if c["passive"] else "false"}, target: {j(c["target"])}, owner: {j(c["owner"])} }},'
    )
lines.append("};")
lines.append("export const MINION_REFS: MinionRef[] = [")
for r in minion_refs:
    hp = "null" if r["hp"] is None else str(r["hp"])
    lines.append(
        f'  {{ name: {j(r["name"])}, id: {j(r["id"])}, hp: {hp}, hpDynamic: {"true" if r["hpDynamic"] else "false"}, '
        f'elem: {j(r["elem"])}, owner: {j(r["owner"])} }},'
    )
lines.append("];")

out = os.path.join(ROOT, "game/web/src/glossref.generated.ts")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"wrote {out}: {len(skill_refs)} skill names ({len(skill_cards)} cards), {len(minion_refs)} minion names")
