"""Generate herometa.generated.ts: hero id -> { name, title } for the character-select showcase.

Splits each roster hero's full character_name into a short NAME and a TITLE (epithet), using
frozen/characters.json's short_name where it's a clean substring, else a comma split, else no title.
Run from repo root: python game/web/tools/gen_herometa.py
"""
import json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
chars = json.load(open(os.path.join(ROOT, "game/content/frozen/characters.json"), encoding="utf-8"))
chars = chars if isinstance(chars, list) else chars.get("characters", chars)


def split(full, short):
    full = (full or "").strip()
    if short and short != full and short in full:
        title = full.replace(short, "", 1).strip().strip(",").strip()
        if title.lower() in ("the", "a", "an", ""):
            return full, ""  # a bare article isn't a title (e.g. "The Black Knight")
        return short, title
    if "," in full:
        n, t = full.split(",", 1)
        return n.strip(), t.strip()
    return full, ""


meta = {}
for c in chars:
    if not c.get("in_roster"):
        continue
    name, title = split(c.get("character_name"), c.get("short_name"))
    meta[c["id"]] = {"name": name, "title": title}

lines = [
    "/**",
    " * hero id -> { name, title } for the character-select showcase (name = proper name, title = epithet).",
    " * Generated by game/web/tools/gen_herometa.py from frozen/characters.json — do not edit by hand.",
    " */",
    "export const HERO_META: Record<string, { name: string; title: string }> = {",
]
for hid in sorted(meta):
    m = meta[hid]
    lines.append(f'  {json.dumps(hid)}: {{ name: {json.dumps(m["name"])}, title: {json.dumps(m["title"])} }},')
lines.append("};")

out = os.path.join(ROOT, "game/web/src/herometa.generated.ts")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"wrote {out}: {len(meta)} heroes ({sum(1 for m in meta.values() if m['title'])} with titles)")
