"""Generate glossary.generated.ts: the mechanical-term definitions for the in-match hover-keyword glossary.

Reads output/glossary.json (definitions: term / definition / Godot colour name / keyword variants) and emits a
compact TS array. Only the definitions are baked in — the skill/minion name references aren't used in-match.
Run from repo root: python game/web/tools/gen_glossary.py
"""
import json, os

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
g = json.load(open(os.path.join(ROOT, "output/glossary.json"), encoding="utf-8"))
defs = g.get("definitions", [])

lines = [
    "/**",
    " * Mechanical-term definitions for the in-match hover-keyword glossary: the term, its definition, the",
    " * source Godot colour name (mapped to a dark-theme hex in glossary.ts), and the keyword variants",
    " * (Stun/Stuns/Stunned/…) that trigger it. Generated by game/web/tools/gen_glossary.py from",
    " * output/glossary.json — do not edit by hand.",
    " */",
    "export interface GlossaryDef { term: string; definition: string; color: string; keywords: string[]; }",
    "export const GLOSSARY_DEFS: GlossaryDef[] = [",
]
for d in defs:
    lines.append(
        "  { term: %s, definition: %s, color: %s, keywords: %s },"
        % (json.dumps(d.get("term", "")), json.dumps(d.get("definition", "")),
           json.dumps(d.get("color", "")), json.dumps(d.get("keywords", [])))
    )
lines.append("];")

out = os.path.join(ROOT, "game/web/src/glossary.generated.ts")
open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
print(f"wrote {out}: {len(defs)} definitions, {sum(len(d.get('keywords', [])) for d in defs)} keyword variants")
