/**
 * Per-effect STATE descriptions for named marks/stacks — what HOLDING the effect does RIGHT NOW,
 * describing the effect itself (never the applying skill's action, a fusion form, or a synergy).
 * Text may contain {generic}/{fire}/… energy tokens, rendered as icons. A variant overrides the base
 * while the bearer holds its `when` status. Authored in effect_descriptions.json; regenerate with
 * gen_effect_desc.py. EFFECT_HIDE = internal bookkeeping flags that show no chip.
 */
export const EFFECT_DESC: Record<string, string> = {
  "A Sprinkle of Recklessness": "Lowers a marked ally's helpful-skill cost or raises a marked enemy's harmful-skill cost by 1 {generic} for 1 turn; the ally gains Elemental Essence if they use a new skill.",
  "A Tale of Joy and Wonder": "Keeper of Fables' allies gain Elemental Essence when they use a new skill.",
  "Acceleration Serum": "After 3 turns, this enemy takes 40 affliction damage.",
  "Acted": "Records that Gommar used a skill this turn, suppressing Natural Cryogenics' idle heal.",
  "Aerie Essence Override": "While Syl's starting Shield holds, she always triggers Two as One when she uses a skill.",
  "Apprenticeborn Pathogen": "Deals 5 damage when applied, lowers the target's damage by 10 the next turn, then stuns them on the final turn.",
  "Arcadia, Enraged": "Deals 5 Affliction damage to all enemies each turn for 4 turns; while active, Thorn Prick costs nothing and deals 5 more initial damage.",
  "Arcadian Advancement": "Each time an ally triggers Prance, Titania's effects permanently last one additional turn.",
  "Arcadian Target": "This enemy is marked as the target of an Arcadian skill.",
  "Banner of Consecration": "For 2 turns, anyone who damages Taryn or his allies takes 10 damage.",
  "Banner of Harmony": "For 1 turn, any Harmful skill this enemy uses is reflected to Taryn.",
  "Blackened Wounds": "This enemy ignores all healing for 1 turn.",
  "Blessed Leylines": "This ally is Invulnerable for 1 turn and permanently receives 5 more healing from all sources.",
  "Blood in the Water": "Holds stored damage; River Daughter's Blood in the Water skill spends it to deal extra damage.",
  "Bloodrose Offering": "For 1 turn, if this ally dies, Maggie heals 10 HP per stack of Curse of Thorns on her.",
  "Bog Witch's Bargain": "If this enemy uses a new skill, it takes 35 Affliction damage and permanently ignores non-damage effects; otherwise it is stunned and Maggie heals 35 HP.",
  "Boon: Save Your Friends": "For 1 turn, this Hero's next Helpful skill heals its targets 15 HP and makes them Invulnerable; using a different skill instead ends this and permanently Isolates the Hero.",
  "Bottled Flame": "Pyrrha holds Bottled Flame for 3 turns.",
  "Bounty": "Allies who deal damage to this enemy are healed for 10 health.",
  "Bramblelash": "Until the end of Maggie's next turn, if this enemy takes new damage, Maggie gains Elemental Essence.",
  "Brimsteel Scabbard": "Jarrik's next Blade of Ashes deals triple damage, cannot be countered, and creates a Cinderling minion if it strikes an enemy affected by Cinders.",
  "Brittle Ice": "Each stack lowers Iceblood Hammer's damage by 5, stacking up to twice.",
  "Burning Blood Serum": "Dennis deals 10 more damage and takes 10 damage per turn, for each stack.",
  "Burning Order": "This Summer Courtesan deals triple damage this turn.",
  "Bypass": "Damage dealt to this unit ignores Invulnerability, Damage Reduction, and Shield.",
  "Call Tides": "A counter on Zev'kir; his water skills grow stronger with each stack of Call Tides.",
  "Capacitor Upgrade": "Ando's Expel Energy deals 5 more damage per stack; all stacks are removed when Expel Energy is used.",
  "Catalytic Nova": "Your next Ripple deals 10 more damage for each stack.",
  "Catalytic Nova Chain": "Increases the damage of River Daughter's next Ripple by 10 per stack; she gains Elemental Essence if Catalytic Nova is used again next turn.",
  "Chains of Atlantis": "This enemy takes 5 Affliction damage per stack during each turn of Call Tides.",
  "Channel Earth": "A stack Gaia accumulates; several of her skills scale with how many times Channel Earth has been used.",
  "Channel Vitality": "Whenever one of Gaia's minions acts this turn, this ally is healed 10 HP.",
  "Charged": "While Charged, Ando's skills are augmented.",
  "Chorus": "Stays active while at least one of Ayana's two Angel minions is alive; ends when both are killed.",
  "Chronicle Deeds": "If this enemy uses a new skill this turn, Tales to Tell gains 35 Shield.",
  "Chronicle Fragments": "When Tales to Tell's Shield breaks from damage, Keeper of Fables gains a Fragment; his abilities spend Fragments as 10 Shield each.",
  "Cinders": "This enemy can be Shattered by Cinderswell and takes Affliction from Call Cinders.",
  "Cinders Proc Lock": "Once-per-turn lock so Cinders' bonus Affliction damage and Elemental Essence trigger only once each turn.",
  "Cloister": "For 1 turn, the Damage Reduction from Revered Daughter is doubled.",
  "Cold and Alone": "This enemy gains a stack each turn while Invulnerable or Isolated, and is stunned for 1 turn upon reaching 3 stacks.",
  "Compound Eyes": "Titania cannot be Blinded, Stunned, or have her costs changed.",
  "Concealed": "Records that a hidden skill stays concealed until it triggers; nothing reads this.",
  "Corrosive Slam": "This unit is charging a 15 Affliction hit on the enemy team next turn; taking damage cancels it.",
  "Curse of Darkness": "This character takes 15 Affliction damage and one stack of Deepening Shadows each turn; if it never uses a skill, Curse of Darkness copies to an ally at its current duration.",
  "Curse of Fealty": "For 3 turns, this unit deals 5 less non-Affliction damage and the Black Knight deals 5 more damage.",
  "Curse of Thorns": "Each stack deals Maggie 5 Affliction damage every turn for the rest of the game.",
  "Cursed Gift": "Any healing this target receives for the next 3 turns is dealt as Affliction damage instead.",
  "Dancing Lights": "While active, Blade of Ashes targets all enemies and Jarrik automatically creates a Cinderling whenever he triggers his Cinders.",
  "Dazzling Lights": "The first enemy to use a skill on Gommar while he is Frost-Covered has its skill costs increased by 1 {generic} for 1 turn.",
  "Dead or Alive": "The Black Knight ignores all new Harmful skills for 1 turn.",
  "Deal: Defeat Your Enemies": "This Hero deals 10 more non-Affliction damage for 1 turn, but takes 20 Affliction damage if they use a new skill.",
  "Deal: Realize Your Potential": "Until the end of their next turn, this Hero's skills cost 1 less Specific and 1 less Generic energy; using a new skill stuns them for 1 turn.",
  "Deal: Save Your Friends": "For 1 turn, this Hero's next Helpful skill heals its targets 15 HP and makes them Invulnerable for 1 turn; using any other new skill instead ends this and permanently Isolates the Hero.",
  "Deepening Shadows": "At the end of each of Laria's turns she gains a stack of Deepening Shadows, but only while she has fewer than 3.",
  "Deja Vu Watch": "This enemy is marked for 1 turn; if the mark expires while still on them, their cooldowns are paralyzed for 2 turns.",
  "Direct Energy Line": "Whenever Saya gains Elemental Essence she heals 10 Health, and cannot be healed otherwise.",
  "Disarming Pitch": "For 1 turn, any enemy who uses a new skill on Scratch becomes marked for 1 turn.",
  "Dive": "River Daughter is under the effect of Dive.",
  "Dive Ripple": "Ripple lasts two turns.",
  "Dive River Clone": "River Clone costs 1 {generic}.",
  "Dive Undertow": "Undertow targets all enemies.",
  "Divine Ire": "Ayana deals 5 more Voice of Light damage to this enemy per stack; a stack is gained whenever they damage her allies.",
  "Divinity Engine": "For Sera's next 2 turns she ignores non-damage effects; during this time Synthetic Skyblade consumes an extra Eyes of Vengeance stack when possible and grants her Shield equal to its damage.",
  "Drakken": "Jarrik can no longer apply, trigger, or consume Cinders.",
  "Drop of Moonglove": "For 1 turn, if this enemy is healed, they permanently ignore healing and take 15 Affliction damage each turn for the rest of the round.",
  "EMG Armed": "Scratch's next non-Ultimate Deal skill will also cast his other two Deal skills.",
  "EMG Fired": "Internal flag marking that this once-only effect has already fired.",
  "Eagle Acted": "Internal marker recording that Syl's Eagle has acted this turn.",
  "Earth Pillar": "This enemy is marked with an Earth Pillar for Roland's next two turns; several of his skills act on marked enemies.",
  "Echoes of Desire": "The next skill this ally uses will occur twice.",
  "Electroblade": "This enemy is marked by Electroblade, singling them out as a target for Ando's Electroblade skills.",
  "Endless Night": "Every skill used by the allied team is Invisible.",
  "Enhanced": "Saya's next skill is Enhanced, triggering its added effect.",
  "Enhanced Saya Coil": "Deals 20 damage to a random enemy at the end of every turn.",
  "Ethereal Form": "The turn after the Black Knight ignores a skill, he deals 10 additional damage.",
  "Evencoin": "This character is treated as having triple their actual stacks of Deepening Shadows.",
  "Evencoin Given": "Records that a killing blow has already granted an Evencoin this battle.",
  "Execution Sentence": "Jarrik can no longer be stunned or countered.",
  "Exile": "This unit is Exiled; using a skill normally ends Exile.",
  "Eyes of Vengeance": "This enemy gains a stack whenever it uses a non-Invisible Harmful skill on Sera or her allies.",
  "Faustian Bargain": "Scratch's next deal will not apply its positive effect to enemies or its Triggered effect to allies.",
  "Faustian: no-trigger": "Internal marker tracking that this Deal has not yet been triggered.",
  "Final Breath": "The first time Jarrik would die, he instead becomes Immortal for one turn.",
  "Five Plagues": "When Titania deals Affliction damage to an enemy, each stack gives a 10% chance to apply a random debuff.",
  "Flames of Judgment": "Enemies gain a stack when they damage Pyrrha via Fan the Flames or use a skill on Pyrrha or her allies.",
  "Flat Design": "This ally was already aided by Character Development this round, so aiding it again gives Keeper no Elemental Essence.",
  "Forced Harmony": "If this target deals new damage to Taryn's allies, it takes double damage from Taryn's next Inspiring Thrust.",
  "Fox Fire": "For 4 turns, each time the marked unit uses or receives a new Harmful skill, an enemy takes 5 Affliction damage or an ally heals 5 HP; a new skill used on Fate gives him Elemental Essence.",
  "Fox's Cunning": "For 1 turn, any enemy that uses a new skill becomes affected by Fox Fire.",
  "Frost-Covered": "Enhances Gommar's skills; if he damages an enemy that has reduced damage, he gains Elemental Essence.",
  "Gift Malice": "While active, Gift from the Fae uses its harmful version.",
  "Godly Wisdom": "Every 3rd time enemies trigger Voice of Light or Prayer, Ayana automatically uses Voice of Glory.",
  "Grasping Vines": "Next turn this enemy takes 15 damage; if they use a skill first, they are also stunned for 1 turn.",
  "Guardian Suppressed": "Protector of the Song's automatic activation is suppressed for 1 turn because Taryn dealt damage.",
  "HS-112 Fury Serum": "For 4 turns, any unit Dennis damages and any unit that damages him is Taunted for 1 turn.",
  "HS-46 Ascendant Serum": "Dennis ignores non-damage effects for 1 turn, and Big Green Fist deals 10 more damage until the end of his next turn.",
  "HS-88 Reconstitution Serum": "Dennis heals 5 HP each turn per stack.",
  "Hallowed Proc Lock": "Internal marker that stops Hallowed Footsteps' bonus from triggering more than once per hit.",
  "Hand of Michael": "Next turn, this enemy takes 30 damage; if they use a harmful skill first, it is Countered and they take 15 more.",
  "Heavenly Parry": "If this enemy uses a new Harmful skill, it takes 25 Piercing damage and gains a stack of Eyes of Vengeance. This effect is invisible.",
  "Hive Formation": "For 4 turns, this ally gains Compound Eyes, and Titania's Barbed Wit Taunt can redirect to a random Hive Formation ally.",
  "Hunger for Battle: Fed": "The Black Knight deals 5 more damage whenever he deals damage; this stacks and is removed if he ends a turn dealing none.",
  "Hysteria Serum": "This enemy is permanently Isolated and takes 20 Affliction damage if it uses a Helpful skill.",
  "Icebite Briars": "For 4 turns, enemies Maggie damages deal 5 less non-Affliction damage for 1 turn, and Curse of Thorns does not damage her.",
  "Iced Shelf": "Keeper of Fables and the target enemy are stunned until a Helpful or Harmful skill is used on either; ending it for one ends it for all.",
  "Icy Shrapnel": "When this mark expires next turn, this enemy takes 20 damage.",
  "Icy Smile": "If this enemy takes new damage this turn, they are stunned and the damaging ally gains Elemental Essence.",
  "In Between CD": "Cooldown marker: In Between's Harmful-effect ignore cannot trigger again for 2 turns.",
  "Inspiring Thrust": "This turn, any ally who uses a new harmful skill on this enemy gains Elemental Essence.",
  "King's Saddle": "For 3 turns, Bjorn, True King is stunned and redirects damage Gommar would take to himself; if Gommar consumes Frost-Covered, Bjorn casts Sovereign's Howl on a random enemy.",
  "Know Your Fate": "For 3 turns, this Hero ignores non-damage effects and their skills cost nothing; at the end, the Hero is killed.",
  "Lens": "This Prismari Ranger is using their Lens; an allied Ranger can reflect their skill through it.",
  "Lens Applied": "Counts the Lens skills that have been used on this enemy this turn.",
  "Lens Target": "This enemy is the Prismari Rangers' Lens target; their reflected and redirected skills strike it.",
  "Lens of the Deep": "For its next two turns, this enemy takes double damage from reflected skills.",
  "Leyline Decay Suppressed": "Leyline Nest's cost no longer decreases each turn; instead it drops by 1 {generic} each time Syl gains Elemental Essence.",
  "Light of Raphael": "For 3 turns, Zephyrex has 20 Shield and Elegant Sweep hits instantly.",
  "Lightning Rod": "Saya deals 5 damage to a random enemy per stack; she gains a stack whenever she gains energy from Elemental Essence.",
  "Lingering Spores": "Deals 5 Affliction damage per turn per stack if this is an enemy, or heals 5 per turn per stack if an ally.",
  "Living Stone": "At the end of each of Roland's turns, he gives 10 Shield to a random ally; if that Shield breaks, he gains Elemental Essence.",
  "Magnetized": "This Boulder taunts all enemies for 1 turn, then next turn deals double damage to any enemy it damages.",
  "Mammon's Flame": "Each use raises Mammon's Flame's cost by 1 {generic} and its damage to the target and Pyrrha by 10.",
  "Mark the Path": "Allies Bypass when targeting this enemy.",
  "Marked": "When a marked target triggers one of Scratch's Deal skills, Scratch gains Elemental Essence; if a Deal expires untriggered, its target gains Elemental Essence.",
  "Mentorship": "For 3 turns, this ally gains 5 increased damage and 5 Damage Reduction, and gains Elemental Essence when they deal damage, take damage, are stunned, or become invulnerable.",
  "Mentorship: dealt": "Tales to Tell's Shield stops protecting Keeper of Fables; when he dies, allies split that Shield.",
  "Mentorship: invuln": "Internal flag: Tales to Tell's Shield no longer protects Keeper of Fables, and on his death his allies split that Shield.",
  "Mentorship: stunned": "Internal flag marking that this mentored ally already earned Elemental Essence from being stunned.",
  "Mentorship: taken": "Tales to Tell's Shield no longer protects Keeper of Fables; when he dies, his allies split that Shield.",
  "Mindfog Serum": "For 3 turns, Dennis's cooldowns rise by 1 and he ignores stuns and counters, while Lumbering Smash stuns its targets' non-Strategic skills for 1 turn.",
  "Mirage Trap: Strategic": "Aramao counters the first Strategic skill this enemy uses within 1 turn.",
  "Mirage Trap: non-Strategic": "Aramao will counter the first non-Strategic skill this enemy uses.",
  "Mooncursed": "This character's Strategic skills are stunned, it deals 5 more non-Affliction damage, and it suffers 10 Affliction damage per turn.",
  "Mutated Strain": "A mutated Apprenticeborn Pathogen whose effects run in reverse order, with double the damage reduction and five times the damage.",
  "Nightcloak Candle": "This ally's skills deal 5 more non-Affliction damage; enemies who use a harmful skill on them take 5 Affliction damage and are marked by Nightcloak Candle.",
  "Not Today": "For 1 turn, harmful skills aimed at this ally are reflected to Taryn instead.",
  "Oathbreaker Primary": "Internal marker tagging Oathbreaker's primary target so the splash damage skips it.",
  "Ominous Rumble": "This enemy is automatically targeted by Arcadian Duet and Jolt, consuming the mark.",
  "Once More: Revived": "Internal marker recording that this Hero has already been revived, preventing another revival.",
  "Opposites Attract": "For 1 turn, helpful skills on this enemy redirect to Ando, and damaging skills on Ando redirect to this enemy.",
  "Overclock": "For 3 turns, after Ando uses a Supercharged skill he becomes Charged and gains Elemental Essence.",
  "Overwatch": "This enemy is an Overwatch target; Orbital Strike deals 20 Bypassing damage to all Overwatch-marked enemies.",
  "Pain Tolerance": "Dennis gains a stack when damaged; each stack increases Big Green Fist's damage by 5.",
  "Pain Tolerance Essence": "Blocks Dennis from gaining Elemental Essence again from Pain Tolerance until his next turn.",
  "Panacea Cycle": "Every 3 turns, Ayana is cleansed of all enemy effects at the end of her turn.",
  "Panic Armed": "Saya's next Stroke of Genius detonates all her inventions, dealing 10 Piercing damage to a random enemy and granting 10 Shield per device detonated.",
  "Panic Spent": "Bookkeeping marker that Saya has spent Panic via Stroke of Genius.",
  "Perfect Execution": "Each stack permanently increases Perfect Execution's damage by 15, gained each time it is used.",
  "Perfection": "Zephyrex holds Perfection until the end of his next turn; if it expires, Perfect Execution is disabled for the rest of the round.",
  "Perfection Locked": "Perfect Execution is disabled for the rest of the round because Perfection expired.",
  "Personal Magnetism": "For 1 turn, Saya counters this enemy's first Helpful or Harmful skill; on success it loses Elemental Essence and gains a matching Magnetic Charge.",
  "Plasma Charge": "Saya gains 40 shield and ignores affliction damage for 1 turn.",
  "Prance": "Counts each time Titania gains or gives Elemental Essence through Prance.",
  "Prance Watch": "The first unit to use a new skill on Titania this turn gains Elemental Essence.",
  "Prayer": "If this ally receives new damage next turn, Ayana gains Elemental Essence.",
  "Prism Sentence": "This enemy is stunned, takes double damage from Voice of Light, and casting Voice of Light on it also hits the enemy team, Bypassing.",
  "Prisma Launch: Bypass": "An internal marker for Prisma Launch with no direct effect on its own.",
  "Prisma Vault": "Crimson Crash deals 15 additional damage to this marked enemy.",
  "Prisma Whirl": "For one turn, the first enemy to use a Harmful skill receives 10 Piercing damage.",
  "Prisma Whirl Barrage": "While active, every enemy that uses a Harmful skill takes 10 Piercing damage.",
  "Prod": "Increases the damage of the next skill this enemy uses on Zephyrex by 10 (does not stack).",
  "Protect Me!": "Harmful skills used on Hector are reflected to Dennis for 1 turn.",
  "Radiant Glory": "For 3 turns, using Stalwart Shield or Inspiring Thrust also casts Refrain on the target.",
  "RangersAlive": "This Hero is Untargetable, ignores damage and Harmful effects, and dies only when all three Rangers are dead.",
  "Reanimated": "This revived ally has their Strategic skills permanently stunned.",
  "Refrain": "On an enemy, stuns their harmful skills for 1 turn; on an ally, heals them 15 whenever they use a skill for 2 turns.",
  "Repulse": "Zev'kir counters the first harmful skill this ally receives; if countered, he begins channeling Call Tides.",
  "Rev Uses": "Counts Rev's uses, up to 3, escalating how many Capacitor Upgrade stacks it generates.",
  "Rising Geyser": "For 3 turns, this enemy replicates all new damage it receives to other Rising Geyser-marked targets.",
  "Rising Indignation": "Gaia's Fury costs 1 {generic} less per stack; at 3 stacks, Gaia's Fury is cast automatically.",
  "Ritual Power": "A Ritual accumulates Ritual Power; reaching its threshold triggers the Ritual's effect.",
  "Ritual Unleashed": "Whenever Elemental Essence is gained, Xyris gains 5 Ritual Power; at 75, all units' skill cooldowns drop by 1.",
  "Ritual of Agony": "Gains 4 Ritual Power whenever a unit takes damage or dies; at 75 Power, all units permanently take double damage.",
  "River Clone": "Counters the first harmful skill this enemy uses; this effect is invisible.",
  "Sacred Grove": "Heals this ally 5 health per turn until they use a Harmful skill; anyone who damages them becomes marked by Sacred Grove.",
  "Saya Coil": "Deals 10 damage to a random enemy at the end of every turn; Saya can have up to 3 Saya Coils active at once.",
  "Scan of the All-Knowing": "For 1 turn, Eyes of Vengeance also triggers from Strategic skills.",
  "Shadow Cross": "Until the end of the turn, Shadow Strike deals 10 more damage to this enemy.",
  "Shadow Rebound": "For 1 turn, the first harmful skill used on this ally is reflected back to its user; hidden until it triggers.",
  "Shadow Seekers": "For 2 turns, if this enemy takes new damage from Syl or her Eagle, their non-Strategic skills are stunned for 1 turn and the mark is removed.",
  "Silent Avenger": "If an allied Hero is killed, Ando immediately becomes Supercharged for his next two turns, and this Supercharge is not consumed by his abilities.",
  "Singularity": "For 2 turns, Ando casts Electroblade on enemies attempting Invulnerability and Flash Step on enemies using harmful skills.",
  "Skylance Empowered": "This turn, Syl's Skylance deals an additional 15 damage.",
  "Somersault: Prisma Launch": "Internal flag noting a Prisma Launch somersault has fired this turn.",
  "Somersault: Prisma Vault": "An internal marker for Somersault with no direct effect on its own.",
  "Somersault: Prisma Whirl": "Records that Prisma Whirl marked Prisma Crimson; holding all three Somersault marks makes Crimson Crash deal 40 more damage.",
  "Somnic Watch": "Xyris counters this enemy's next Harmful skill for 1 turn, then creates a Dream Reflection minion copying it.",
  "Soulsteal": "For 3 turns, this enemy becomes Invulnerable for 1 turn at the end of each of their turns.",
  "Spectral Growth": "This enemy gains a stack whenever it uses a Strategic skill; Maggie's damaging skills remove the stacks to heal her 5 HP per stack.",
  "Spider Mine": "If this enemy uses a new skill, its attached spider mine detonates for 15 damage.",
  "Spirit Away": "For Laria's next two turns, triggering In Between also applies its effects to this hero; if an enemy, they first take 25 true damage.",
  "Stalwart Shield": "Harmful skills aimed at this ally are reflected to Taryn instead.",
  "Stonefield Stalker": "A charge Roland accumulates from using Earth Pillar or launching Boulders with Strength From The Earth.",
  "Stoneform": "While marked, Boulders launched with Strength From The Earth deal double damage.",
  "Stun Immunity": "Jarrik cannot be stunned or countered.",
  "Sulphur Vent": "Counters the first enemy to use a skill on Pyrrha this turn; if countered, adds a Fan the Flames stack.",
  "Supercharged": "Ando is Supercharged, giving his skills their Supercharged effects for 1 turn.",
  "Sweet Torment": "Maggie deals 5 more non-Affliction damage per stack.",
  "Syl Acted": "Tracks that Syl has acted this turn, used to check whether she and her Eagle acted together.",
  "TINTE Armed": "For 2 turns, the first time Fate or an ally would die they return to 40 HP, then heal 5 HP per active Fox Fire; once per round.",
  "TINTE Spent": "Internal marker recording that Fate's TINTE has been spent.",
  "The Nightmare Rides": "For 2 turns, the Black Knight is invulnerable, and Oathbreaker Strike targets all enemies and is always enhanced.",
  "The Storm Builds": "Galazax's damaging skills apply a stack of The Storm Builds.",
  "The Whimsy Engine": "For 1 turn, whenever a unit uses a new skill, it instead uses a random one of its skills at random targets.",
  "This Is Not The End": "For 2 turns, the first time Fate or an ally would die they return to 40 HP, then heal 5 HP per active Fox Fire; triggers once per round.",
  "To Your Health!": "For 2 turns, if this enemy uses a skill, they take 15 Affliction damage and are stunned for 1 turn; if it ends untriggered, Hector and the enemy team heal 15 HP.",
  "To the Skies": "This turn, Talon Rake stuns its target for 1 turn and gains 1 cooldown, and Soar lasts an additional turn and extends this effect.",
  "Trial of the Sands": "For 3 turns, allied Heroes are Veiled at the end of each turn, and Aramao uses Desert Knife on any enemy that uses a Harmful skill on him.",
  "Twisted Nightmares": "For 1 turn, this enemy's AOE skills become single-target.",
  "Undertow Stun": "Next turn, Undertow will stun its target for 1 turn.",
  "Universal Energy Conduit": "A random allied Hero will gain Elemental Essence.",
  "Verse of Accusation": "Until the end of Taryn's next turn, Banner of Harmony affects all enemies.",
  "Voice of Glory": "Voice of Light and Prayer permanently last 1 additional turn each; this effect stacks.",
  "Voice of Light": "If this enemy deals new damage this turn, Ayana gains Elemental Essence.",
  "Will-o'-wisp": "Fate's team gains 10 Shield for 2 turns; enemies using a new Harmful skill on them take 10 Affliction damage.",
  "Wind Dancer": "Lowers this enemy's non-Affliction damage by 10 for 1 turn; if they use a new harmful skill during it, Zephyrex gains Elemental Essence.",
  "Wind Step Window": "Internal timing window for triggering Wind Step.",
  "Wraith in White": "For 2 turns Pyrrha ignores non-damage effects, and using Pyrokinesis on an enemy first uses Fan the Flames.",
  "chargeHandled": "Internal flag marking that Ando's charge state has been handled this turn.",
  "noOverclockConvert": "Internal flag that stops Ando's Overclock from converting his Charge state during this step.",
};

export interface EffectVariant { when: string; text: string; }
export const EFFECT_VARIANT: Record<string, EffectVariant> = {
  "Universal Energy Conduit": { when: "Enhanced", text: "A random allied Hero will gain Elemental Essence and their skills will cost 1 less {generic} for 1 turn." },
};

export const EFFECT_HIDE: ReadonlySet<string> = new Set([
  "Acted",
  "Aerie Essence Override",
  "Chronicle Deeds",
  "Cinders Proc Lock",
  "Concealed",
  "Deja Vu Watch",
  "EMG Armed",
  "EMG Fired",
  "Eagle Acted",
  "Evencoin Given",
  "Faustian: no-trigger",
  "Hallowed Proc Lock",
  "In Between CD",
  "Leyline Decay Suppressed",
  "Mentorship: dealt",
  "Mentorship: invuln",
  "Mentorship: stunned",
  "Mentorship: taken",
  "Mirage Trap: Strategic",
  "Oathbreaker Primary",
  "Once More: Revived",
  "Pain Tolerance Essence",
  "Panic Spent",
  "Prisma Launch: Bypass",
  "Repulse",
  "Rev Uses",
  "Somersault: Prisma Launch",
  "Somersault: Prisma Vault",
  "Somersault: Prisma Whirl",
  "Syl Acted",
  "TINTE Spent",
  "Wind Step Window",
  "chargeHandled",
  "noOverclockConvert",
]);
