/**
 * Per-effect STATE descriptions for named marks/stacks — what HOLDING the effect does, describing the
 * effect itself (never the applying skill's action). Authored in effect_descriptions.json; regenerate
 * with game/web/tools/gen_effect_desc.py. EFFECT_HIDE = internal bookkeeping flags that show no chip.
 */
export const EFFECT_DESC: Record<string, string> = {
  "A Sprinkle of Recklessness": "An ally's helpful skills are cheaper and grant Elemental Essence when used; an enemy's Harmful skills cost more.",
  "A Tale of Joy and Wonder": "For two turns, Keeper's allies gain Elemental Essence whenever they use a new skill.",
  "Acceleration Serum": "A ticking dose that detonates for 40 affliction damage after 3 turns.",
  "Acted": "Marks that Gommar has already taken an action this turn.",
  "Aerie Essence Override": "While her starting Shield holds, Syl always triggers Two as One when she uses a skill, even acting alone.",
  "Apprenticeborn Pathogen": "Dennis's spreading infection: it burns you now, saps your damage next turn, then stuns you after.",
  "Arcadia, Enraged": "While Enraged, Arcadia's Thorn Prick is free and Enhanced, and every enemy burns for 5 each turn.",
  "Arcadian Advancement": "Permanently extends the duration of Titania's effects \u2014 each stack makes them last one additional turn.",
  "Arcadian Target": "Singled out and marked as a target for a hero's follow-up attack.",
  "Banner of Consecration": "For 2 turns, anyone who damages Taryn or his allies takes 10 damage in return.",
  "Banner of Harmony": "The enemy's Harmful skills reflect back onto Taryn, and damaging his allies leaves them open to double Inspiring Thrust damage.",
  "Blackened Wounds": "Wounds that won't close \u2014 all incoming healing is ignored while marked.",
  "Blessed Leylines": "Permanently receives 5 more healing from all sources.",
  "Blood in the Water": "A reservoir of stored damage that Run Red empties to strike far harder.",
  "Bloodrose Offering": "If this ally dies this turn, Maggie heals 10 HP for each Curse of Thorns stack she holds.",
  "Bog Witch's Bargain": "Use a new skill to take 35 Affliction and permanently ignore non-damage effects, or stay idle and be stunned.",
  "Boon: Save Your Friends": "This Hero's next Helpful skill heals its targets 15 HP and makes them Invulnerable for a turn.",
  "Bottled Flame": "While Pyrrha holds it, damaging an enemy adds lingering Affliction damage.",
  "Bounty": "Shattered, and any ally who deals damage to this enemy is healed for 10 health.",
  "Bramblelash": "Snared by Maggie's thorns \u2014 damaging it feeds her Elemental Essence and it takes extra from Thornburst and Ghostlash.",
  "Brimsteel Scabbard": "Jarrik's next Blade of Ashes deals triple damage, can't be countered, and spawns a Cinderling on Cinders-marked foes.",
  "Brittle Ice": "A fragile coating of ice that leaves the bearer prone to shattering.",
  "Burning Blood Serum": "The bearer deals extra damage each turn, but bleeds 10 damage per stack held.",
  "Burning Order": "This Summer Courtesan deals triple damage this turn.",
  "Bypass": "This damage ignores shields, Invulnerability, and other defenses that would otherwise block it.",
  "Call Tides": "Zev'kir's rising tide \u2014 each stack empowers his water skills and unlocks stuns and Essence.",
  "Capacitor Upgrade": "Stores bonus damage for Ando's next Expel Energy, then clears when it fires.",
  "Catalytic Nova": "Stored power that adds damage to River Daughter's next Ripple, stacking infinitely.",
  "Catalytic Nova Chain": "River Daughter's next Ripple hits harder, and reusing Catalytic Nova next turn grants her Elemental Essence.",
  "Chains of Atlantis": "Each stack bleeds 5 Affliction damage per turn and leaves the enemy open to Abyssal Grasp's stun.",
  "Channel Earth": "Gaia's growing earth charge \u2014 each buildup strengthens Worldfist and Rampart's Shield and heals her minions.",
  "Channel Vitality": "This ally is healed 10 HP whenever one of Gaia's minions acts this turn.",
  "Charged": "Ando's skills are augmented and he ignores non-damage effects; using a skill Supercharges him for a stronger effect.",
  "Chorus": "Ayana's angelic Chorus is active, sustained while either summoned Angel lives and ending when both fall.",
  "Chronicle Deeds": "Invisibly watches this enemy \u2014 if it uses a new skill this turn, Tales to Tell gains 35 Shield.",
  "Chronicle Fragments": "Stored shield salvage worth 10 each; Keeper of Fables' skills spend it and cost less per fragment.",
  "Cinders": "Marked for Jarrik's flame \u2014 his skills Shatter, burn, and tax the bearer's Strategic skills.",
  "Cinders Proc Lock": "Once-per-turn lock so Jarrik's Cinders bonus damage and Essence trigger only once each turn.",
  "Cloister": "The Damage Reduction granted by Revered Daughter is doubled while this holds.",
  "Cold and Alone": "Frost builds each turn spent Invulnerable or Isolated, stunning at 3 stacks and drawing Winter's Bite.",
  "Compound Eyes": "Titania cannot be Blinded, Stunned, or have her skill costs changed.",
  "Concealed": "The bearer is concealed, hidden from enemy view.",
  "Corrosive Slam": "Charging a delayed 15 Affliction hit on the enemy team next turn \u2014 cancelled if this unit takes damage.",
  "Curse of Darkness": "Each turn deals 15 Affliction and a Deepening Shadows stack; failing to act spreads the curse to an ally.",
  "Curse of Fealty": "Deals 5 less non-Affliction damage while the Black Knight deals 5 more, and never counts as acting alongside him.",
  "Curse of Thorns": "Burns Maggie for Affliction each turn, but fuels her shields and thorn skills.",
  "Cursed Gift": "Either heals the bearer 20 HP each turn, or turns any healing they receive into Affliction damage.",
  "Dancing Lights": "Jarrik is ablaze \u2014 Blade of Ashes strikes every enemy and his Cinder minions ignore harmful skills.",
  "Dazzling Lights": "The first enemy to strike Frost-Covered Gommar has its skill costs spiked by 65 for a turn.",
  "Dead or Alive": "The Black Knight ignores all new harmful skills, and while enhanced redirects allies' harmful skills onto himself.",
  "Deal: Defeat Your Enemies": "The Hero deals more damage and ignores stuns and counters, but using a new skill burns them for Affliction.",
  "Deal: Realize Your Potential": "The bearer's skills cost 1 less Specific and 1 less Generic, but using a new skill self-stuns them for a turn.",
  "Deal: Save Your Friends": "This Hero's next Helpful skill also heals its targets 15 HP and makes them Invulnerable for a turn.",
  "Deepening Shadows": "Amplifies Laria's night skills \u2014 each stack adds to their healing, damage, or detonation.",
  "Deja Vu Watch": "A lingering sense of repetition, waiting for a past moment to recur.",
  "Direct Energy Line": "Saya heals 10 whenever she gains Elemental Essence, and can be healed no other way.",
  "Disarming Pitch": "Scratch holds Shield and reflexively marks any enemy who uses a new skill on him for his Deal skills.",
  "Dive": "River Daughter deals 10 piercing damage to enemies who use harmful skills, and empowers skills cast from it.",
  "Dive Ripple": "Next turn River Daughter's skills surge \u2014 Ripple lasts longer, Undertow hits all enemies, and River Clone costs less.",
  "Dive River Clone": "Next turn Ripple lingers longer, Undertow hits all enemies, and River Clone costs less.",
  "Dive Undertow": "River Daughter's next-turn skills are empowered \u2014 Ripple lasts longer, Undertow hits all enemies, and River Clone costs less.",
  "Divine Ire": "Ayana's Voice of Light deals 5 more damage per buildup, growing as enemies harm her allies.",
  "Divinity Engine": "Sera ignores non-damage effects while her Synthetic Skyblade shields her and drains an extra Eyes of Vengeance stack.",
  "Drakken": "Jarrik can no longer apply, trigger, or consume Cinders.",
  "Drop of Moonglove": "If the marked enemy is healed, they permanently ignore healing and burn 15 Affliction each turn.",
  "EMG Armed": "Armed and primed to release its stored effect.",
  "EMG Fired": "Internal flag tracking that the EMG has already fired.",
  "Eagle Acted": "Internal flag marking that Syl's Eagle has acted this turn.",
  "Earth Pillar": "Marked for Roland's Boulders, which launch at it, and it can suffer Affliction over time.",
  "Echoes of Desire": "The bearer's next skill will occur twice.",
  "Electroblade": "Tagged for Ando's lightning \u2014 his skills chain to you, striking, Shattering, Bypassing, and Afflicting the marked.",
  "Endless Night": "For two turns, every skill the allied team uses is Invisible.",
  "Enhanced": "Saya's skills gain bonus effects while Enhanced.",
  "Enhanced Saya Coil": "An empowered coil striking a random enemy for doubled damage each turn's end.",
  "Ethereal Form": "The Black Knight's Ghostblade pierces, and he deals 10 extra damage the turn after ignoring a skill.",
  "Evencoin": "The round's first killer's brand \u2014 tripling their effective Deepening Shadows and drawing extra Midnight Justice damage.",
  "Evencoin Given": "Holding an Evencoin, the bearer counts as having triple its actual Deepening Shadows stacks.",
  "Execution Sentence": "A death sentence \u2014 every skill the enemy uses burns a stack, and at zero they are instantly killed.",
  "Exile": "Removed from the fight \u2014 using a skill would normally end this exiled state.",
  "Eyes of Vengeance": "Marked for Sera's vengeance \u2014 her skills consume stacks for bonus damage, cooldown reductions, and effects.",
  "Faustian Bargain": "Scratch's next deal withholds its positive effect from enemies and its Triggered effect from allies.",
  "Faustian: no-trigger": "Internal bookkeeping lock that keeps the Faustian deal from triggering.",
  "Final Breath": "The first time Jarrik would die, he becomes Immortal for one turn instead.",
  "Five Plagues": "Each stack raises the chance Titania's Affliction damage inflicts a random plague effect.",
  "Flames of Judgment": "Pyrrha's judgment mounting toward execution \u2014 at 7 stacks, Judgment Day instantly kills you.",
  "Flat Design": "Marks an ally Character Development already aided this round, so aiding them again earns Keeper no Essence.",
  "Forced Harmony": "If it damages Taryn's allies, it takes double damage from her next Inspiring Thrust.",
  "Fox Fire": "Marked by Fate's flame; using or receiving a Harmful skill burns enemies or heals allies.",
  "Fox's Cunning": "Use a new skill and you catch Fox Fire; stay idle and your cooldowns are paralyzed for 2 turns.",
  "Frost-Covered": "Gommar's skills are enhanced, and while frost clings to him he ignores non-damage effects.",
  "Gift Malice": "Titania's Gift from the Fae is toggled to its harmful version.",
  "Godly Wisdom": "Counts enemy triggers of Voice of Light or Prayer; every third makes Ayana auto-cast Voice of Glory.",
  "Grasping Vines": "Vines close in \u2014 the bearer takes 15 damage next turn and is stunned if they act.",
  "Guardian Suppressed": "Guardian at the Gates is switched off this turn because Taryn dealt damage.",
  "HS-112 Fury Serum": "Anyone Dennis damages, or who damages Dennis, is Taunted for a turn.",
  "HS-46 Ascendant Serum": "Dennis shrugs off non-damage effects while his Big Green Fist strikes for extra damage.",
  "HS-88 Reconstitution Serum": "Heals Dennis 5 HP each turn, more with every stack.",
  "Hallowed Proc Lock": "Internal once-per-turn lock for Hallowed Footsteps' bonus damage and healing.",
  "Hand of Michael": "Doomed to take 30 damage next turn; using a harmful skill is Countered for 15 more.",
  "Heavenly Parry": "Using a Harmful skill triggers 25 Piercing damage and an Eyes of Vengeance stack; the enemy also deals 10 reduced damage next turn.",
  "Hive Formation": "Grants Compound Eyes and can absorb the Taunt redirect from Titania's Barbed Wit.",
  "Hunger for Battle: Fed": "The Black Knight deals 5 more damage per stack, lost if he ends a turn dealing none.",
  "Hysteria Serum": "Permanently Isolated, and takes 20 Affliction damage whenever they use a Helpful skill.",
  "Icebite Briars": "Maggie's hits weaken enemy damage for a turn, while her own Curse of Thorns stops hurting her.",
  "Iced Shelf": "Keeper of Fables and its target share a stun until any Helpful or Harmful skill breaks it for all.",
  "Icy Shrapnel": "Embedded shards of ice that leave the bearer wounded and exposed.",
  "Icy Smile": "If the marked enemy takes new damage this turn, they are stunned and the attacker gains Elemental Essence.",
  "In Between CD": "Marks In Between on cooldown, blocking Laria's Harmful-ignore trigger.",
  "Inspiring Thrust": "Allies who land a new harmful skill on this marked enemy gain Elemental Essence.",
  "King's Saddle": "Bjorn is stunned but soaks the damage Gommar would take, answering consumed Frost-Covered with Sovereign's Howl.",
  "Know Your Fate": "Ignores non-damage effects and pays no skill costs, then is killed when it expires.",
  "Lens": "This Prismari Ranger is aiming; allies can reflect their skills through it, amplified.",
  "Lens Applied": "A focusing lens is active, amplifying effects on the bearer.",
  "Lens Target": "Designated as the Prismari Rangers' Lens target, so their reflected and redirected skills strike this enemy.",
  "Lens of the Deep": "For its next two turns it takes double damage from reflected skills.",
  "Leyline Decay Suppressed": "Leyline Nest's cost falls when Stormchaser gains Elemental Essence instead of each turn.",
  "Light of Raphael": "Zephyrex holds 20 Shield and his Elegant Sweep strikes instantly.",
  "Lightning Rod": "Saya shocks a random enemy each turn, hitting harder as Elemental Essence energy charges the rod.",
  "Lingering Spores": "Ticks 5 Affliction each turn on enemies (5 healing on allies) and hastens Dennis's Serums.",
  "Living Stone": "Bound to Roland's stone \u2014 the bearer is shielded and healed each turn, empowering his stone skills on it.",
  "Magnetized": "The marked Boulder taunts all enemies, then deals double damage to whatever it strikes next turn.",
  "Mammon's Flame": "Each use escalates Mammon's Flame, raising its energy cost and the damage dealt to the target and Pyrrha.",
  "Mark the Path": "Roland's allies Bypass defenses when attacking this enemy, and Final Warning can strike it.",
  "Marked": "Bound by one of Scratch's Deals \u2014 triggering it feeds him Essence, letting it expire feeds you.",
  "Mentorship": "Gains 5 damage and 5 Damage Reduction, and gathers Elemental Essence from combat events.",
  "Mentorship: dealt": "Internal counter tracking damage dealt for Keeper of Fables' mentorship.",
  "Mentorship: invuln": "Internal flag tracking a mentorship-granted invulnerability between Keeper of Fables and his allies.",
  "Mentorship: stunned": "Internal flag marking that this mentored ally already earned Essence from being stunned.",
  "Mentorship: taken": "Internal counter tracking Mentorship damage taken.",
  "Mindfog Serum": "Dennis ignores stuns and counters for 3 turns, though his cooldowns are raised.",
  "Mirage Trap: Strategic": "Aramao will counter the first Strategic skill this enemy uses.",
  "Mirage Trap: non-Strategic": "Aramao is poised to counter this enemy's next non-Strategic skill.",
  "Mooncursed": "Strategic skills stunned, deals 5 more non-Affliction damage, and suffers 10 Affliction each turn.",
  "Mutated Strain": "A reversed, supercharged pathogen: it stuns first, then doubly weakens, then deals fivefold damage.",
  "Nightcloak Candle": "The marked ally's skills deal 5 more non-Affliction damage, and enemies who attack them are punished.",
  "Not Today": "For 1 turn, harmful skills aimed at this ally are reflected onto Taryn instead.",
  "Oathbreaker Primary": "Designates the primary target of Oathbreaker's effect.",
  "Ominous Rumble": "Zephyrex's storm-marked target, automatically struck by Arcadian Duet and Jolt and feeding him Essence.",
  "Once More: Revived": "Marks that a Once More revival has already been used.",
  "Opposites Attract": "Helpful skills on this enemy reflect to Ando, and damage to Ando reflects back to it.",
  "Overclock": "Ando loops his charge \u2014 each Supercharged skill drops him back to Charged and grants Elemental Essence.",
  "Overwatch": "Marked for Orbital Strike, which deals 20 Bypassing damage to all Overwatch-marked enemies.",
  "Pain Tolerance": "Each stack sharpens Dennis's Big Green Fist, adding 5 damage per stack.",
  "Pain Tolerance Essence": "Hector treats this Hero as Dennis, redirecting his Dennis skills here and skipping his minion.",
  "Panacea Cycle": "Counts down Ayana's cleanse cycle \u2014 every third turn she sheds all enemy effects at turn's end.",
  "Panic Armed": "Saya's next Stroke of Genius will detonate all her inventions for Piercing damage and Shield.",
  "Panic Spent": "Marks that Saya has already spent her panic bonus this battle.",
  "Perfect Execution": "Builds with each flawless piercing strike, sustaining Zephyrex's Perfection and his chain of executions.",
  "Perfection": "Zephyrex is immune to stuns and keeps Perfect Execution usable; letting it expire disables that skill.",
  "Perfection Locked": "Perfection is locked, preventing any further progress toward it.",
  "Personal Magnetism": "Saya counters this enemy's next skill; on success it loses Elemental Essence and gains a matching Magnetic Charge.",
  "Plasma Charge": "Saya's charged shield absorbs affliction, and damage to it grants her Elemental Essence.",
  "Prance": "Tracks Elemental Essence traded through Prance, spent by Summer Clique to summon Courtesans.",
  "Prance Watch": "For one turn, the first unit to use a new skill on Titania gains Elemental Essence.",
  "Prayer": "Ayana's blessing rests on this ally \u2014 if they take new damage next turn, Ayana gains Elemental Essence.",
  "Prism Sentence": "Stunned for two turns, taking double damage from Voice of Light (which also spreads to allies); invisible skills become visible.",
  "Prisma Launch: Bypass": "Internal flag that bypasses the Prisma Launch step.",
  "Prisma Vault": "Prisma Crimson is invulnerable for one turn behind the defensive vault.",
  "Prisma Whirl": "The first enemy to use a Harmful skill takes 10 Piercing damage.",
  "Prisma Whirl Barrage": "The bearer is caught in a whirling barrage of prismatic strikes.",
  "Prod": "Goaded \u2014 the enemy's next skill used on Zephyrex deals 10 more damage.",
  "Protect Me!": "Harmful skills used on Hector are reflected onto Dennis for the turn.",
  "Radiant Glory": "The hero's Stalwart Shield and Inspiring Thrust also cast Refrain on their target.",
  "RangersAlive": "Tracks the living Prismari Rangers; the hero falls only when all three are gone.",
  "Reanimated": "Revived as the Black Knight's thrall with Strategic skills permanently stunned, granting him 15 DR.",
  "Refrain": "On an enemy, silences their harmful skills; on an ally, heals them each time they act.",
  "Repulse": "Zev'kir counters the first harmful skill the bearer receives.",
  "Rev Uses": "Internal counter tracking Rev uses, scaling Capacitor Upgrade generation up to three.",
  "Rising Geyser": "Linked to other marked enemies \u2014 all new damage you receive is replicated to them.",
  "Rising Indignation": "Each stack cuts the cost of Gaia's Fury; at three stacks it fires automatically.",
  "Ritual Power": "Charges a hero's Ritual toward the threshold that unleashes its devastating effect.",
  "Ritual Unleashed": "Xyris gains Ritual Power on every Essence gain, cutting all cooldowns at 75.",
  "Ritual of Agony": "Pyrrha's Ritual gains Ritual Power from every hit and death, building toward permanently doubled damage for all units.",
  "River Clone": "An invisible clone counters the first harmful skill against the bearer, then triggers River Daughter's Ripple.",
  "Sacred Grove": "Allies heal 5 each turn until they attack; enemy attackers get marked for Gaia's Expel Intruders.",
  "Saya Coil": "Each active coil zaps a random enemy for 10 damage at the end of every turn.",
  "Scan of the All-Knowing": "Eyes of Vengeance also triggers from Strategic skills while this lasts.",
  "Shadow Cross": "Marked by Laria \u2014 Shadow Strike deals increased damage to this enemy until end of turn.",
  "Shadow Rebound": "The first harmful skill used on this ally is reflected back at its caster.",
  "Shadow Seekers": "New damage from Syl or her Eagle stuns the marked enemy's non-Strategic skills.",
  "Silent Avenger": "Ando instantly Supercharges when an ally dies, and Penance strikes through Shield as Piercing.",
  "Singularity": "For 2 turns, Ando casts Electroblade on enemies going Invulnerable and Flash Step on harmful attackers.",
  "Skylance Empowered": "Skylance is empowered, strengthening its next use.",
  "Somersault: Prisma Launch": "Internal flag noting a Prisma Launch somersault has fired this turn.",
  "Somersault: Prisma Vault": "Internal flag marking the Prisma Vault somersault state.",
  "Somersault: Prisma Whirl": "Flags that the Prismari Ranger's Prisma Whirl somersault is ready to react.",
  "Somnic Watch": "Xyris will counter this enemy's next Harmful skill, spawning a Dream Reflection that copies it.",
  "Soulsteal": "The bearer becomes Invulnerable for a turn at the end of each of their next three turns.",
  "Spectral Growth": "Maggie's damaging skills consume these stacks to heal her 5 HP each.",
  "Spider Mine": "An attached mine detonates for 15 damage the moment the bearer uses a new skill.",
  "Spirit Away": "When Laria triggers In Between, its effects also strike the marked hero \u2014 enemies first take 25 true damage.",
  "Stalwart Shield": "Shielded by Taryn \u2014 harmful skills against the bearer reflect back to him, and it can heal or grant invulnerability on ending.",
  "Stonefield Stalker": "Charges built from Earth Pillars and Boulders, spent to extend how long Roland stays Mooncursed.",
  "Stoneform": "Hardened to stone \u2014 Boulders launched by Strength From The Earth deal double damage.",
  "Stun Immunity": "Jarrik cannot be stunned or countered.",
  "Sulphur Vent": "Pyrrha counters the first enemy to use a skill on her, adding Fan the Flames to them.",
  "Supercharged": "Ando is at peak charge \u2014 his skills are fully augmented, striking all enemies and dealing bonus damage.",
  "Sweet Torment": "Permanently raises Maggie's non-Affliction damage by 5 per stack, gained each time she harms an ally.",
  "Syl Acted": "Internal flag marking that Syl has acted this turn.",
  "TINTE Armed": "The next lethal blow to Fate or an ally is denied, reviving them to 40 HP.",
  "TINTE Spent": "Internal flag marking that Fate's TINTE has already been spent.",
  "The Nightmare Rides": "The Black Knight is invulnerable while his Oathbreaker Strike hits every enemy, always enhanced.",
  "The Storm Builds": "Storm charge that Galazax's skills relocate and consume to unleash Piercing damage.",
  "The Whimsy Engine": "Skills misfire \u2014 any skill the bearer uses becomes a random one aimed at random targets.",
  "This Is Not The End": "The next time Fate or an ally would die, they instead revive at 40 HP, healing more per Fox Fire.",
  "To Your Health!": "For 2 turns, if this enemy uses any skill they take 15 Affliction damage and are stunned for 1 turn.",
  "To the Skies": "While active, Talon Rake stuns its target and Soar lasts an extra turn.",
  "Trial of the Sands": "For 3 turns Aramao's team Veils each turn while he counters attackers with Desert Knife.",
  "Twisted Nightmares": "The enemy's AOE skills are reduced to single-target.",
  "Undertow Stun": "Primes Undertow to stun its target next turn.",
  "Universal Energy Conduit": "Each stack feeds Saya's Prismatic Energy Cannon for +10 damage while channeling Elemental Essence to her allies.",
  "Verse of Accusation": "Until the end of Taryn's next turn, his Banner of Harmony reaches every enemy.",
  "Voice of Glory": "Each stack permanently extends Voice of Light and Prayer by one turn.",
  "Voice of Light": "Marked by Ayana's light; dealing new damage triggers her Essence gain and retribution.",
  "Will-o'-wisp": "Fate's team holds 10 Shield, and enemies who strike them with new Harmful skills take 10 Affliction damage.",
  "Wind Dancer": "The bearer moves with wind-swift, dancing grace.",
  "Wind Step Window": "An open window during which a Wind Step response can be triggered.",
  "Wraith in White": "Pyrrha ignores non-damage effects, burns the enemy team for 5 Affliction each turn, and empowers Pyrokinesis.",
  "chargeHandled": "Internal flag marking that Ando's charge state has already been resolved this turn.",
  "noOverclockConvert": "Internal flag blocking Ando's Overclock from converting his Charge state this step.",
};

export const EFFECT_HIDE: ReadonlySet<string> = new Set([
  "Acted",
  "Chronicle Deeds",
  "Cinders Proc Lock",
  "Deja Vu Watch",
  "EMG Fired",
  "Eagle Acted",
  "Faustian: no-trigger",
  "Hallowed Proc Lock",
  "In Between CD",
  "Mentorship: dealt",
  "Mentorship: invuln",
  "Mentorship: stunned",
  "Mentorship: taken",
  "Once More: Revived",
  "Panic Spent",
  "Prisma Launch: Bypass",
  "Repulse",
  "Rev Uses",
  "Somersault: Prisma Launch",
  "Somersault: Prisma Vault",
  "Somersault: Prisma Whirl",
  "Syl Acted",
  "TINTE Spent",
  "Wind Step Window",
  "chargeHandled",
  "noOverclockConvert",
]);
