/**
 * Mechanical-term definitions for the in-match hover-keyword glossary: the term, its definition, the
 * source Godot colour name (mapped to a dark-theme hex in glossary.ts), and the keyword variants
 * (Stun/Stuns/Stunned/…) that trigger it. Generated by game/web/tools/gen_glossary.py from
 * output/glossary.json — do not edit by hand.
 */
export interface GlossaryDef { term: string; definition: string; color: string; keywords: string[]; }
export const GLOSSARY_DEFS: GlossaryDef[] = [
  { term: "Affliction Damage", definition: "This type of damage ignores Damage Reduction and Shield, but is commonly not affected by damage-boosting effects.", color: "RED", keywords: ["Affliction"] },
  { term: "Blind", definition: "If a Hero with this effect uses a single-target skill (that isn't self-target only), their target will be selected at random from all available, valid targets.", color: "BISQUE", keywords: ["Blinding", "Blinded", "Blinds", "Blind"] },
  { term: "Bypassing", definition: "Skills and units with this effect will ignore Invulnerability and Isolation when selecting targets.", color: "DARK_GRAY", keywords: ["Bypassing", "Bypasses"] },
  { term: "Channel", definition: "A class of skill that is cancelled if its user is Stunned or uses a new skill.", color: "DARK_CYAN", keywords: ["Channeling", "Channeled", "Channels", "Channel"] },
  { term: "Control", definition: "A class of skill that is cancelled if its user is Stunned.", color: "SKY_BLUE", keywords: ["Controlling", "Controlled", "Controls", "Control"] },
  { term: "Counter", definition: "A triggered effect that, once activated, negates the use of a skill and places that skill on Cooldown.", color: "ORANGE", keywords: ["Countering", "Countered", "Counters", "Counter"] },
  { term: "Damage Ignore", definition: "A unit with this effect will ignore all forms of damage, regardless of the source.", color: "INDIAN_RED", keywords: ["ignores all damage"] },
  { term: "Damage Mod", definition: "Increases or decreases a unit's damage by the displayed amount. Does not modify True damage.", color: "MEDIUM_AQUAMARINE", keywords: ["Damage Mods"] },
  { term: "Damage Reduction", definition: "Reduces the displayed amount from damaging skills or effects. Does not apply to Piercing damage, Affliction damage, or True damage.", color: "CORNFLOWER_BLUE", keywords: ["Damage Reduction"] },
  { term: "Elemental Essence", definition: "A Hero with this effect will generate an energy of their Element at the start of their turn.", color: "GOLD", keywords: ["Elemental Essence"] },
  { term: "Harmful", definition: "A class of skill that targets enemy units.", color: "DARK_RED", keywords: ["Harmful"] },
  { term: "Helpful", definition: "A class of skill that targts allied units.", color: "LIGHT_BLUE", keywords: ["Helpful"] },
  { term: "Immortal", definition: "A unit with this effect cannot have their HP decreased lower than 1 through damage or other effects.", color: "GOLD", keywords: ["Immortal"] },
  { term: "Invulnerable", definition: "An effect that prevents a unit from being targeted with new Harmful skills.", color: "AQUAMARINE", keywords: ["Invulnerability", "Invulnerable"] },
  { term: "Isolated", definition: "An effect that prevents a unit from being targeted with new Helpful skills.", color: "REBECCA_PURPLE", keywords: ["Isolating", "Isolation", "Isolated", "Isolates", "Isolate"] },
  { term: "Minion", definition: "A type of unit created by a Hero. They can act normally, but do not generate energy at the start of the turn. Each player has a maximum of 6 minions on the field.", color: "GREEN_YELLOW", keywords: ["minions", "minion"] },
  { term: "Non-Damage Ignore", definition: "A Hero with this effect cannot be affected by harmful negative effects (damage is not considered an effect.) This includes damage mods, cost changes, Stuns, Blinds, Isolation, Shatter, Taunt, Paralysis, and Silence, but has no effect on Triggered effects or Counters.", color: "LIGHT_SALMON", keywords: ["ignores non-damage"] },
  { term: "Paralysis", definition: "An effect that causes a unit's skills to not advance their Cooldowns each turn.", color: "AQUA", keywords: ["Paralyzing", "Paralysis", "Paralyzed", "Paralyzes", "Paralyze"] },
  { term: "Piercing Damage", definition: "This type of damage ignores Damage Reduction on its target. Interacts normally with Shield and damage boosts.", color: "YELLOW", keywords: ["Piercing"] },
  { term: "Reflect", definition: "A variety of Counter effect that changes the target of the skill to the displayed unit.", color: "GOLDENROD", keywords: ["Reflecting", "Reflected", "Reflects", "Reflect"] },
  { term: "Shatter", definition: "An effect that prevents a unit from benefitting from Damage Reduction, Invulnerability, or Shield.", color: "YELLOW", keywords: ["Shattered", "Shatters", "Shatter"] },
  { term: "Shield", definition: "Absorbs up to the displayed amount from damaging skills or effects. Does not apply to Affliction damage.", color: "GREEN", keywords: ["Shield"] },
  { term: "Silence", definition: "An effect that stops a unit from generating energy of their Element using Elemental Essence.", color: "DIM_GRAY", keywords: ["Silencing", "Silenced", "Silences", "Silence"] },
  { term: "Stealth", definition: "Units with this effect will not Trigger enemy effects.", color: "DARK_BLUE", keywords: ["Stealthing", "Stealthed", "Stealth"] },
  { term: "Strategic", definition: "A class of skill that is either exclusively self-targeting or isn't specifically Harmful or Helpful.", color: "DIM_GRAY", keywords: ["Strategic"] },
  { term: "Stun", definition: "Prevents a unit from using skills on their turn. Some only affect certain classes of skills, or affect all but a certain class.", color: "CORAL", keywords: ["Stunning", "Stunned", "Stuns", "Stun"] },
  { term: "Taunt", definition: "An effect that forces a unit to target another specified unit. Has no effect on skills that target multiple units.", color: "SADDLE_BROWN", keywords: ["Taunting", "Taunted", "Taunts", "Taunt"] },
  { term: "Triggered Effect", definition: "An effect that is activated by another action or event, such as dealing or receiving damage, using skills, dying, or being countered. Units that are Stealthed cannot activate these effects if they were created by an enemy.", color: "CADET_BLUE", keywords: ["Triggering", "Triggered", "Triggers", "Trigger"] },
  { term: "Veiled", definition: "An effect that hides a Hero's details until they use a Harmful skill.", color: "TAN", keywords: ["Veiled"] },
];
