/**
 * hero id -> { name, title } for the character-select showcase (name = proper name, title = epithet).
 * Generated by game/web/tools/gen_herometa.py from frozen/characters.json — do not edit by hand.
 */
export const HERO_META: Record<string, { name: string; title: string }> = {
  "ando": { name: "Ando-91", title: "" },
  "aramao": { name: "Aramao", title: "Spectre of the Sands" },
  "ayana": { name: "Ayana", title: "Voice of Light" },
  "blackknight": { name: "The Black Knight", title: "" },
  "dennis": { name: "Dennis", title: "the Apprentice" },
  "fate": { name: "Fate", title: "Reborn Hero" },
  "gaia": { name: "Gaia", title: "Worldsoul" },
  "galazax": { name: "Galazax", title: "the Coming Storm" },
  "gommar": { name: "Gommar", title: "Frostfang Chieftain" },
  "hector": { name: "Hector", title: "the Injector" },
  "jarrik": { name: "Jarrik", title: "Cinderblade" },
  "keeper": { name: "Keeper", title: "of Fables" },
  "laria": { name: "Laria", title: "Nightcloaked" },
  "maggie": { name: "Maggie", title: "Thorncursed" },
  "pyrrha": { name: "Pyrrha", title: "the Mage in Ivory" },
  "riverdaughter": { name: "The River Daughter", title: "" },
  "roland": { name: "Roland", title: "Geolord" },
  "saya": { name: "Saya", title: "Genius Inventor" },
  "scratch": { name: "Scratch", title: "Crossroads Dealer" },
  "sera": { name: "SERAFIA MKI", title: "" },
  "syl": { name: "Syl", title: "Scourge of the Skies" },
  "taryn": { name: "Taryn", title: "Hand of Glory" },
  "titania": { name: "Titania", title: "Laughing Princess" },
  "trinity": { name: "Prisma Trinity", title: "Prismari Rangers" },
  "xyris": { name: "Xyris", title: "King of Dreams" },
  "zephyrex": { name: "Zephyrex", title: "the Windblade" },
  "zevkir": { name: "Zev'kir", title: "Tidecaller" },
};
