/**
 * Browser transport for Quick Match: a thin, typed wrapper around the platform WebSocket that speaks the
 * shared protocol (../../net/protocol.ts). It only moves JSON messages — all match logic lives in main.ts,
 * which subscribes to `onMessage` and drives the existing board rendering from the server's authoritative
 * state. Nothing here simulates the game.
 */
import type { ClientMsg, Profile, ServerMsg } from "../../net/protocol.ts";
import { DEFAULT_PORT, parseMessage } from "../../net/protocol.ts";

export class MatchSocket {
  private ws: WebSocket;
  onMessage?: (msg: ServerMsg) => void;
  onOpen?: () => void;
  onClose?: () => void;
  onError?: () => void;

  constructor(url: string) {
    this.ws = new WebSocket(url);
    this.ws.addEventListener("open", () => this.onOpen?.());
    this.ws.addEventListener("close", () => this.onClose?.());
    this.ws.addEventListener("error", () => this.onError?.());
    this.ws.addEventListener("message", (ev: MessageEvent) => {
      const msg = parseMessage<ServerMsg>(String(ev.data));
      if (msg) this.onMessage?.(msg);
    });
  }

  send(msg: ClientMsg): void {
    if (this.ws.readyState === WebSocket.OPEN) this.ws.send(JSON.stringify(msg));
  }

  close(): void {
    try { this.ws.close(); } catch { /* already closing */ }
  }
}

/**
 * Where to reach the match server. Overridable (so a GitHub-Pages-hosted client can point at any server):
 *   ?server=wss://host        query param  (highest priority)
 *   localStorage.arenaServer  persisted override
 * else ws://<page-host>:8790  the local-dev default.
 */
export function serverUrl(): string {
  const fromQuery = new URLSearchParams(location.search).get("server");
  if (fromQuery) return fromQuery;
  const stored = localStorage.getItem("arenaServer");
  if (stored) return stored;
  const host = location.hostname || "localhost";
  const scheme = location.protocol === "https:" ? "wss" : "ws"; // match the page so an https client isn't mixed-content-blocked
  return `${scheme}://${host}:${DEFAULT_PORT}`;
}

/** The http(s) origin matching serverUrl (ws→http, wss→https) — for the /profile endpoint. */
export function httpBase(): string {
  return serverUrl().replace(/^ws/, "http").replace(/\/+$/, "");
}

export interface AvatarInfo { file: string; name: string; }

/** The pickable player avatars — read from the static manifest generated by tools/build_avatars.py. */
export async function fetchAvatars(): Promise<AvatarInfo[]> {
  try {
    const res = await fetch("../../assets/avatars/manifest.json", { cache: "no-cache" });
    if (!res.ok) return [];
    const list = (await res.json()) as AvatarInfo[];
    return Array.isArray(list) ? list.filter((a) => a && typeof a.file === "string") : [];
  } catch {
    return [];
  }
}

/**
 * Fetch (create-or-verify) the guest profile over HTTP, so the team-select screen can show a name + record
 * without opening a match socket. Returns null if the server is unreachable or the identity is refused.
 */
export async function fetchProfile(playerId: string, secret: string, name: string): Promise<Profile | null> {
  try {
    // text/plain avoids a CORS preflight; the server reads the body as JSON.
    const res = await fetch(`${httpBase()}/profile`, { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify({ playerId, secret, name }) });
    if (!res.ok) return null;
    return ((await res.json()) as { profile: Profile }).profile ?? null;
  } catch {
    return null;
  }
}

/** A successful register/login: the account profile plus the {playerId, secret} identity to store + reuse. */
export interface AuthCreds { profile: Profile; playerId: string; secret: string; }
export type AuthReply = { ok: true; creds: AuthCreds } | { ok: false; error: string };

async function postAuth(path: string, body: object): Promise<AuthReply> {
  try {
    const res = await fetch(`${httpBase()}${path}`, { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify(body) });
    const data = (await res.json().catch(() => ({}))) as { profile?: Profile; playerId?: string; secret?: string; error?: string };
    if (res.ok && data.profile && data.playerId && data.secret) return { ok: true, creds: { profile: data.profile, playerId: data.playerId, secret: data.secret } };
    return { ok: false, error: data.error || "request failed" };
  } catch {
    return { ok: false, error: "can't reach the server" };
  }
}
/** Register a new account (returns a fresh {playerId, secret} identity) or an error message. */
export const register = (username: string, password: string, name: string): Promise<AuthReply> => postAuth("/register", { username, password, name });
/** Log into an existing account (returns a fresh {playerId, secret} identity) or an error message. */
export const login = (username: string, password: string): Promise<AuthReply> => postAuth("/login", { username, password });

/** Claim the CURRENT (guest) identity: attach a username + password so the existing record/progress carries
 *  over. Keeps the same {playerId, secret}; returns the now-registered profile or an error message. */
export const claimAccount = (playerId: string, secret: string, username: string, password: string): Promise<AuthReply> =>
  postAuth("/claim", { playerId, secret, username, password });

/** Persist synced profile fields (display name / avatar / progress) to the account. Fire-and-forget-safe. */
export async function saveProfile(playerId: string, secret: string, patch: { name?: string; avatar?: string; progress?: unknown }): Promise<Profile | null> {
  try {
    const res = await fetch(`${httpBase()}/save`, { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify({ playerId, secret, ...patch }) });
    if (!res.ok) return null;
    return ((await res.json()) as { profile: Profile }).profile ?? null;
  } catch {
    return null;
  }
}
