/**
 * Browser transport for Quick Match: a thin, typed wrapper around the platform WebSocket that speaks the
 * shared protocol (../../net/protocol.ts). It only moves JSON messages — session logic lives in pvp-controller.ts,
 * which subscribes to `onMessage` and drives the existing board rendering from the server's authoritative
 * state. Nothing here simulates the game.
 */
import type { ClientMsg, Profile, ServerMsg } from "../../net/protocol.ts";
import { DEFAULT_PORT, parseMessage } from "../../net/protocol.ts";

export class MatchSocket {
  private ws: WebSocket;
  onMessage?: (msg: ServerMsg) => void;
  onOpen?: () => void;
  onClose?: () => void;
  onError?: () => void;

  constructor(url: string) {
    this.ws = new WebSocket(url);
    this.ws.addEventListener("open", () => this.onOpen?.());
    this.ws.addEventListener("close", () => this.onClose?.());
    this.ws.addEventListener("error", () => this.onError?.());
    this.ws.addEventListener("message", (ev: MessageEvent) => {
      const msg = parseMessage<ServerMsg>(String(ev.data));
      if (msg) this.onMessage?.(msg);
    });
  }

  send(msg: ClientMsg): void {
    if (this.ws.readyState === WebSocket.OPEN) this.ws.send(JSON.stringify(msg));
  }

  close(): void {
    try { this.ws.close(); } catch { /* already closing */ }
  }
}

/**
 * Deployment endpoint: <meta name="arena-server" content="wss://trusted-host">,
 * otherwise ws(s)://<page-host>:8790. URL overrides are restricted to the trusted origin;
 * local development may also change its port. Stored arbitrary overrides are no longer accepted.
 */
export function serverUrl(): string {
  const configured = document.querySelector<HTMLMetaElement>('meta[name="arena-server"]')?.content;
  return resolveServerUrl(location.href, configured);
}

/** URL parameters may select a port/path on the trusted host, never an arbitrary credential recipient. */
export function resolveServerUrl(pageUrl: string, configured?: string): string {
  const page = new URL(pageUrl);
  const relative = configured?.startsWith("/") && !configured.startsWith("//");
  const fallback = relative ? new URL(configured!, page).href.replace(/^http/, "ws") :
    configured || `${page.protocol === "https:" ? "wss" : "ws"}://${page.hostname || "localhost"}:${DEFAULT_PORT}`;
  const trusted = new URL(fallback);
  if (!["ws:", "wss:"].includes(trusted.protocol) || trusted.username || trusted.password) throw new Error("Invalid configured arena server");
  const candidate = page.searchParams.get("server");
  if (candidate) {
    try {
      const url = new URL(candidate);
      const local = ["localhost", "127.0.0.1", "[::1]"].includes(page.hostname);
      if ((url.origin === trusted.origin || (local && url.hostname === trusted.hostname && url.protocol === trusted.protocol)) && !url.username && !url.password) return url.href;
    } catch { /* use configured host */ }
  }
  return trusted.href.replace(/\/$/, "");
}

/** The http(s) origin matching serverUrl (ws→http, wss→https) — for the /profile endpoint. */
export function httpBase(): string {
  return new URL(serverUrl()).origin.replace(/^ws/, "http");
}

export interface AvatarInfo { file: string; name: string; }

/** The pickable player avatars — read from the static manifest generated by tools/build_avatars.py. */
export async function fetchAvatars(): Promise<AvatarInfo[]> {
  try {
    const res = await fetch("../../assets/avatars/manifest.json", { cache: "no-cache" });
    if (!res.ok) return [];
    const list = (await res.json()) as AvatarInfo[];
    return Array.isArray(list) ? list.filter((a) => a && typeof a.file === "string") : [];
  } catch {
    return [];
  }
}

/**
 * Fetch (create-or-verify) the guest profile over HTTP, so the team-select screen can show a name + record
 * without opening a match socket. Returns null if the server is unreachable or the identity is refused.
 */
export async function fetchProfile(playerId: string, secret: string, name: string): Promise<Profile | null> {
  try {
    // text/plain avoids a CORS preflight; the server reads the body as JSON.
    const res = await fetch(`${httpBase()}/profile`, { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify({ playerId, secret, name }) });
    if (!res.ok) return null;
    return ((await res.json()) as { profile: Profile }).profile ?? null;
  } catch {
    return null;
  }
}

/** A successful register/login: the account profile plus the {playerId, secret} identity to store + reuse. */
export interface AuthCreds { profile: Profile; playerId: string; secret: string; }
export type AuthReply = { ok: true; creds: AuthCreds } | { ok: false; error: string };

async function postAuth(path: string, body: object): Promise<AuthReply> {
  try {
    const res = await fetch(`${httpBase()}${path}`, { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify(body) });
    const data = (await res.json().catch(() => ({}))) as { profile?: Profile; playerId?: string; secret?: string; error?: string };
    if (res.ok && data.profile && data.playerId && data.secret) return { ok: true, creds: { profile: data.profile, playerId: data.playerId, secret: data.secret } };
    return { ok: false, error: data.error || "request failed" };
  } catch {
    return { ok: false, error: "can't reach the server" };
  }
}
/** Register a new account (returns a fresh {playerId, secret} identity) or an error message. */
export const register = (username: string, password: string, name: string): Promise<AuthReply> => postAuth("/register", { username, password, name });
/** Log into an existing account (returns a fresh {playerId, secret} identity) or an error message. */
export const login = (username: string, password: string): Promise<AuthReply> => postAuth("/login", { username, password });

/** Claim the CURRENT (guest) identity: attach a username + password so the existing record/progress carries
 *  over. Keeps the same {playerId, secret}; returns the now-registered profile or an error message. */
export const claimAccount = (playerId: string, secret: string, username: string, password: string): Promise<AuthReply> =>
  postAuth("/claim", { playerId, secret, username, password });

/** Persist synced profile fields (display name / avatar / progress) to the account. Fire-and-forget-safe. */
export async function saveProfile(playerId: string, secret: string, patch: { name?: string; avatar?: string; progress?: unknown }): Promise<Profile | null> {
  try {
    const res = await fetch(`${httpBase()}/save`, { method: "POST", headers: { "content-type": "text/plain" }, body: JSON.stringify({ playerId, secret, ...patch }) });
    if (!res.ok) return null;
    return ((await res.json()) as { profile: Profile }).profile ?? null;
  } catch {
    return null;
  }
}
