// GENERATED from content/frozen/elements.json (fusion_recipes) — do not edit by hand.
// Maps an unordered base-element pair "a|b" (sorted) to the fused result element.
const RECIPES: Record<string, string> = {
  "earth|earth": "life",
  "earth|fire": "sun",
  "earth|holy": "sanctuary",
  "earth|ice": "myth",
  "earth|lightning": "magnet",
  "earth|poison": "spore",
  "earth|shadow": "moon",
  "earth|unholy": "grave",
  "earth|water": "slime",
  "earth|wind": "nomad",
  "fire|fire": "dragon",
  "fire|holy": "judgment",
  "fire|ice": "apocalypse",
  "fire|lightning": "plasma",
  "fire|poison": "brimstone",
  "fire|shadow": "ritual",
  "fire|unholy": "devil",
  "fire|water": "alchemy",
  "fire|wind": "mechanic",
  "holy|holy": "divine",
  "holy|ice": "prism",
  "holy|lightning": "vengeance",
  "holy|poison": "antidote",
  "holy|shadow": "vigilante",
  "holy|unholy": "zealot",
  "holy|water": "anointment",
  "holy|wind": "angel",
  "ice|ice": "crystal",
  "ice|lightning": "aurora",
  "ice|poison": "stasis",
  "ice|shadow": "night",
  "ice|unholy": "lich",
  "ice|water": "glacier",
  "ice|wind": "winter",
  "lightning|lightning": "thunder",
  "lightning|poison": "battery",
  "lightning|shadow": "ion",
  "lightning|unholy": "reanimation",
  "lightning|water": "current",
  "lightning|wind": "storm",
  "poison|poison": "evolution",
  "poison|shadow": "assassin",
  "poison|unholy": "blight",
  "poison|water": "serum",
  "poison|wind": "faerie",
  "shadow|shadow": "dimension",
  "shadow|unholy": "curse",
  "shadow|water": "mirror",
  "shadow|wind": "ninja",
  "unholy|unholy": "evil",
  "unholy|water": "blood",
  "unholy|wind": "ghost",
  "water|water": "ocean",
  "water|wind": "mist",
  "wind|wind": "cloud",
};

/** The fused result element for two base elements (order-independent), or undefined if none. */
export function fusionResult(a: string, b: string): string | undefined {
  return RECIPES[[a, b].sort().join("|")];
}
